//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGSTilesMapping {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGSTilesMapping.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 文件已存在 的本地化字符串。
        /// </summary>
        internal static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无空间参考系 的本地化字符串。
        /// </summary>
        internal static string CoorNotSupported {
            get {
                return ResourceManager.GetString("CoorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}路径为空 的本地化字符串。
        /// </summary>
        internal static string DirectoryIsEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}路径不为空 的本地化字符串。
        /// </summary>
        internal static string DirectoryIsntEmpty {
            get {
                return ResourceManager.GetString("DirectoryIsntEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string DoesntExist {
            get {
                return ResourceManager.GetString("DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值在0-19之间 的本地化字符串。
        /// </summary>
        internal static string MaxLError {
            get {
                return ResourceManager.GetString("MaxLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值在0-19之间 的本地化字符串。
        /// </summary>
        internal static string MinLError {
            get {
                return ResourceManager.GetString("MinLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 参数为空 的本地化字符串。
        /// </summary>
        internal static string OptionIsEmpty {
            get {
                return ResourceManager.GetString("OptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数解析错误 的本地化字符串。
        /// </summary>
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键退出 的本地化字符串。
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 为空 的本地化字符串。
        /// </summary>
        internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建路径失败 {0}. 路径:{1} 的本地化字符串。
        /// </summary>
        internal static string UnableToCreate {
            get {
                return ResourceManager.GetString("UnableToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小级别比最大级别大 的本地化字符串。
        /// </summary>
        internal static string ValueError {
            get {
                return ResourceManager.GetString("ValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}文件后缀名错误 的本地化字符串。
        /// </summary>
        internal static string WrongExtension {
            get {
                return ResourceManager.GetString("WrongExtension", resourceCulture);
            }
        }
    }
}
